//! Report generation for PQC readiness analysis.
//!
//! Produces both machine-readable (JSON) and human-readable (text) reports
//! from an `AnalysisResult`.

use crate::analyzer::AnalysisResult;
use crate::crypto::PqcStatus;
use serde_json;

/// Output format for reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReportFormat {
    Json,
    Text,
}

/// Generate a report string from an analysis result.
pub fn generate(result: &AnalysisResult, format: ReportFormat) -> String {
    match format {
        ReportFormat::Json => generate_json(result),
        ReportFormat::Text => generate_text(result),
    }
}

fn generate_json(result: &AnalysisResult) -> String {
    serde_json::to_string_pretty(result).unwrap_or_else(|e| format!("{{\"error\": \"{}\"}}", e))
}

fn generate_text(result: &AnalysisResult) -> String {
    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "{}\n",
        "=".repeat(72)
    ));
    out.push_str("  PQC-Ready IoT Protocol Analyzer -- Analysis Report\n");
    out.push_str(&format!(
        "{}\n\n",
        "=".repeat(72)
    ));

    // Summary
    out.push_str(&format!("  PQC Readiness Score:  {}/100\n", result.score));
    out.push_str(&format!("  Risk Level:           {}\n", result.risk_level));
    out.push_str(&format!("  Packets Analyzed:     {}\n", result.packets_analyzed));
    out.push_str(&format!(
        "  Primitives Detected:  {}\n",
        result.detected_primitives.len()
    ));
    out.push_str(&format!(
        "  Recommendations:      {}\n\n",
        result.recommendations.len()
    ));

    // Score bar
    out.push_str("  Score: [");
    let filled = (result.score as usize * 40) / 100;
    for i in 0..40 {
        if i < filled {
            out.push('#');
        } else {
            out.push('-');
        }
    }
    out.push_str(&format!("] {}/100\n\n", result.score));

    // Category breakdown
    if !result.category_scores.is_empty() {
        out.push_str(&format!("{}\n", "-".repeat(72)));
        out.push_str("  Category Breakdown\n");
        out.push_str(&format!("{}\n\n", "-".repeat(72)));
        out.push_str(&format!(
            "  {:<24} {:>6} {:>6} {:>6} {:>6}\n",
            "Category", "Score", "Safe", "Vuln", "Unk"
        ));
        out.push_str(&format!("  {}\n", "-".repeat(54)));

        for cs in &result.category_scores {
            out.push_str(&format!(
                "  {:<24} {:>5}% {:>6} {:>6} {:>6}\n",
                cs.category.to_string(),
                cs.score,
                cs.safe_count,
                cs.vulnerable_count,
                cs.unknown_count
            ));
        }
        out.push('\n');
    }

    // Detected primitives
    if !result.detected_primitives.is_empty() {
        out.push_str(&format!("{}\n", "-".repeat(72)));
        out.push_str("  Detected Cryptographic Primitives\n");
        out.push_str(&format!("{}\n\n", "-".repeat(72)));
        out.push_str(&format!(
            "  {:<22} {:<20} {:<20} {}\n",
            "Algorithm", "Category", "PQC Status", "Source"
        ));
        out.push_str(&format!("  {}\n", "-".repeat(68)));

        for p in &result.detected_primitives {
            let status_marker = match p.pqc_status {
                PqcStatus::QuantumSafe => "[SAFE]",
                PqcStatus::QuantumVulnerable => "[VULN]",
                PqcStatus::Unknown => "[????]",
            };
            out.push_str(&format!(
                "  {:<22} {:<20} {:<20} {}\n",
                p.algorithm,
                p.category.to_string(),
                status_marker,
                p.source.to_string()
            ));
        }
        out.push('\n');
    }

    // Recommendations
    if !result.recommendations.is_empty() {
        out.push_str(&format!("{}\n", "-".repeat(72)));
        out.push_str("  PQC Migration Recommendations\n");
        out.push_str(&format!("{}\n\n", "-".repeat(72)));

        for (i, rec) in result.recommendations.iter().enumerate() {
            out.push_str(&format!("  {}. {} --> {}\n", i + 1, rec.classical, rec.quantum_safe));
            out.push_str(&format!("     Standard: {}\n", rec.nist_standard));
            out.push_str(&format!("     {}\n\n", rec.notes));
        }
    }

    // Footer
    out.push_str(&format!("{}\n", "=".repeat(72)));
    out.push_str("  Generated by pqc-iot-analyzer v0.1.0\n");
    out.push_str("  https://github.com/amarsohail/pqc-iot-analyzer\n");
    out.push_str(&format!("{}\n", "=".repeat(72)));

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyzer;
    use crate::protocols::{ParsedPacket, ProtocolType, TlsRecord};

    fn sample_result() -> AnalysisResult {
        let packet = ParsedPacket {
            protocol: ProtocolType::CoAP,
            header_summary: "test".into(),
            payload: Vec::new(),
            tls_record: Some(TlsRecord {
                content_type: 22,
                version_major: 0xFE,
                version_minor: 0xFD,
                cipher_suite: Some(0xC02F),
                fragment: Vec::new(),
            }),
            metadata: Vec::new(),
        };
        analyzer::analyze(&[packet])
    }

    #[test]
    fn json_report_is_valid_json() {
        let result = sample_result();
        let json = generate(&result, ReportFormat::Json);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(parsed.get("score").is_some());
        assert!(parsed.get("detected_primitives").is_some());
    }

    #[test]
    fn text_report_contains_sections() {
        let result = sample_result();
        let text = generate(&result, ReportFormat::Text);
        assert!(text.contains("PQC Readiness Score"));
        assert!(text.contains("Category Breakdown"));
        assert!(text.contains("Detected Cryptographic Primitives"));
        assert!(text.contains("PQC Migration Recommendations"));
    }

    #[test]
    fn text_report_shows_score() {
        let result = sample_result();
        let text = generate(&result, ReportFormat::Text);
        assert!(text.contains(&format!("{}/100", result.score)));
    }
}
